version: '3.9'

services:
    db:
        image: fried_shrimp:1.0-db
        container_name: mariaDB
        ports:
            - "3340:3306"
        volumes:
            - data:/var/lib/mysql
        networks:
            - net

    pma:
        image: fried_shrimp:1.0-pma
        container_name: phpMyAdmin
        ports:
            - "8885:80"
        networks:
            - net

networks:
    net:
        driver: bridge

volumes:
    data:
        driver: local